# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import agent_pb2 as agent__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub(object):
    """─── AgentService — implemented by every agent runtime ───

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Init = channel.unary_unary(
                '/hivekernel.agent.AgentService/Init',
                request_serializer=agent__pb2.InitRequest.SerializeToString,
                response_deserializer=agent__pb2.InitResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/hivekernel.agent.AgentService/Shutdown',
                request_serializer=agent__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=agent__pb2.ShutdownResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/hivekernel.agent.AgentService/Heartbeat',
                request_serializer=agent__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=agent__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.Execute = channel.stream_stream(
                '/hivekernel.agent.AgentService/Execute',
                request_serializer=agent__pb2.ExecuteInput.SerializeToString,
                response_deserializer=agent__pb2.TaskProgress.FromString,
                _registered_method=True)
        self.Interrupt = channel.unary_unary(
                '/hivekernel.agent.AgentService/Interrupt',
                request_serializer=agent__pb2.InterruptRequest.SerializeToString,
                response_deserializer=agent__pb2.InterruptResponse.FromString,
                _registered_method=True)
        self.DeliverMessage = channel.unary_unary(
                '/hivekernel.agent.AgentService/DeliverMessage',
                request_serializer=agent__pb2.AgentMessage.SerializeToString,
                response_deserializer=agent__pb2.MessageAck.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """─── AgentService — implemented by every agent runtime ───

    """

    def Init(self, request, context):
        """Lifecycle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request_iterator, context):
        """Execution — bidirectional stream for syscalls during execution
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Interrupt(self, request, context):
        """Interrupt current task (SIGINT)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeliverMessage(self, request, context):
        """Receive message from another agent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Init': grpc.unary_unary_rpc_method_handler(
                    servicer.Init,
                    request_deserializer=agent__pb2.InitRequest.FromString,
                    response_serializer=agent__pb2.InitResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=agent__pb2.ShutdownRequest.FromString,
                    response_serializer=agent__pb2.ShutdownResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=agent__pb2.HeartbeatRequest.FromString,
                    response_serializer=agent__pb2.HeartbeatResponse.SerializeToString,
            ),
            'Execute': grpc.stream_stream_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=agent__pb2.ExecuteInput.FromString,
                    response_serializer=agent__pb2.TaskProgress.SerializeToString,
            ),
            'Interrupt': grpc.unary_unary_rpc_method_handler(
                    servicer.Interrupt,
                    request_deserializer=agent__pb2.InterruptRequest.FromString,
                    response_serializer=agent__pb2.InterruptResponse.SerializeToString,
            ),
            'DeliverMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.DeliverMessage,
                    request_deserializer=agent__pb2.AgentMessage.FromString,
                    response_serializer=agent__pb2.MessageAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hivekernel.agent.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hivekernel.agent.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """─── AgentService — implemented by every agent runtime ───

    """

    @staticmethod
    def Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivekernel.agent.AgentService/Init',
            agent__pb2.InitRequest.SerializeToString,
            agent__pb2.InitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivekernel.agent.AgentService/Shutdown',
            agent__pb2.ShutdownRequest.SerializeToString,
            agent__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivekernel.agent.AgentService/Heartbeat',
            agent__pb2.HeartbeatRequest.SerializeToString,
            agent__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Execute(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/hivekernel.agent.AgentService/Execute',
            agent__pb2.ExecuteInput.SerializeToString,
            agent__pb2.TaskProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Interrupt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivekernel.agent.AgentService/Interrupt',
            agent__pb2.InterruptRequest.SerializeToString,
            agent__pb2.InterruptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeliverMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivekernel.agent.AgentService/DeliverMessage',
            agent__pb2.AgentMessage.SerializeToString,
            agent__pb2.MessageAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
