# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import agent_pb2 as agent__pb2
from . import core_pb2 as core__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in core_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoreServiceStub(object):
    """─── CoreService — provided by core, called by agents ───

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SpawnChild = channel.unary_unary(
                '/hivekernel.core.CoreService/SpawnChild',
                request_serializer=agent__pb2.SpawnRequest.SerializeToString,
                response_deserializer=agent__pb2.SpawnResponse.FromString,
                _registered_method=True)
        self.KillChild = channel.unary_unary(
                '/hivekernel.core.CoreService/KillChild',
                request_serializer=agent__pb2.KillRequest.SerializeToString,
                response_deserializer=agent__pb2.KillResponse.FromString,
                _registered_method=True)
        self.GetProcessInfo = channel.unary_unary(
                '/hivekernel.core.CoreService/GetProcessInfo',
                request_serializer=core__pb2.ProcessInfoRequest.SerializeToString,
                response_deserializer=core__pb2.ProcessInfo.FromString,
                _registered_method=True)
        self.ListChildren = channel.unary_unary(
                '/hivekernel.core.CoreService/ListChildren',
                request_serializer=core__pb2.ListChildrenRequest.SerializeToString,
                response_deserializer=core__pb2.ListChildrenResponse.FromString,
                _registered_method=True)
        self.SendMessage = channel.unary_unary(
                '/hivekernel.core.CoreService/SendMessage',
                request_serializer=agent__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=agent__pb2.SendMessageResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/hivekernel.core.CoreService/Subscribe',
                request_serializer=core__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=agent__pb2.AgentMessage.FromString,
                _registered_method=True)
        self.StoreArtifact = channel.unary_unary(
                '/hivekernel.core.CoreService/StoreArtifact',
                request_serializer=agent__pb2.StoreArtifactRequest.SerializeToString,
                response_deserializer=agent__pb2.StoreArtifactResponse.FromString,
                _registered_method=True)
        self.GetArtifact = channel.unary_unary(
                '/hivekernel.core.CoreService/GetArtifact',
                request_serializer=agent__pb2.GetArtifactRequest.SerializeToString,
                response_deserializer=agent__pb2.GetArtifactResponse.FromString,
                _registered_method=True)
        self.ListArtifacts = channel.unary_unary(
                '/hivekernel.core.CoreService/ListArtifacts',
                request_serializer=core__pb2.ListArtifactsRequest.SerializeToString,
                response_deserializer=core__pb2.ListArtifactsResponse.FromString,
                _registered_method=True)
        self.GetResourceUsage = channel.unary_unary(
                '/hivekernel.core.CoreService/GetResourceUsage',
                request_serializer=core__pb2.ResourceUsageRequest.SerializeToString,
                response_deserializer=core__pb2.ResourceUsage.FromString,
                _registered_method=True)
        self.RequestResources = channel.unary_unary(
                '/hivekernel.core.CoreService/RequestResources',
                request_serializer=core__pb2.ResourceRequest.SerializeToString,
                response_deserializer=core__pb2.ResourceResponse.FromString,
                _registered_method=True)
        self.Escalate = channel.unary_unary(
                '/hivekernel.core.CoreService/Escalate',
                request_serializer=agent__pb2.EscalateRequest.SerializeToString,
                response_deserializer=agent__pb2.EscalateResponse.FromString,
                _registered_method=True)
        self.Log = channel.unary_unary(
                '/hivekernel.core.CoreService/Log',
                request_serializer=agent__pb2.LogRequest.SerializeToString,
                response_deserializer=agent__pb2.LogResponse.FromString,
                _registered_method=True)
        self.ReportMetric = channel.unary_unary(
                '/hivekernel.core.CoreService/ReportMetric',
                request_serializer=core__pb2.MetricRequest.SerializeToString,
                response_deserializer=core__pb2.MetricResponse.FromString,
                _registered_method=True)
        self.ExecuteTask = channel.unary_unary(
                '/hivekernel.core.CoreService/ExecuteTask',
                request_serializer=core__pb2.ExecuteTaskRequest.SerializeToString,
                response_deserializer=core__pb2.ExecuteTaskResponse.FromString,
                _registered_method=True)
        self.SubscribeEvents = channel.unary_stream(
                '/hivekernel.core.CoreService/SubscribeEvents',
                request_serializer=core__pb2.SubscribeEventsRequest.SerializeToString,
                response_deserializer=core__pb2.ProcessEvent.FromString,
                _registered_method=True)
        self.AddCron = channel.unary_unary(
                '/hivekernel.core.CoreService/AddCron',
                request_serializer=core__pb2.AddCronRequest.SerializeToString,
                response_deserializer=core__pb2.AddCronResponse.FromString,
                _registered_method=True)
        self.RemoveCron = channel.unary_unary(
                '/hivekernel.core.CoreService/RemoveCron',
                request_serializer=core__pb2.RemoveCronRequest.SerializeToString,
                response_deserializer=core__pb2.RemoveCronResponse.FromString,
                _registered_method=True)
        self.ListCron = channel.unary_unary(
                '/hivekernel.core.CoreService/ListCron',
                request_serializer=core__pb2.ListCronRequest.SerializeToString,
                response_deserializer=core__pb2.ListCronResponse.FromString,
                _registered_method=True)


class CoreServiceServicer(object):
    """─── CoreService — provided by core, called by agents ───

    """

    def SpawnChild(self, request, context):
        """Process management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KillChild(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProcessInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChildren(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """IPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreArtifact(self, request, context):
        """Shared memory
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArtifact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListArtifacts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResourceUsage(self, request, context):
        """Resources
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestResources(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Escalate(self, request, context):
        """Escalation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Log(self, request, context):
        """Logging
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportMetric(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteTask(self, request, context):
        """Task execution
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeEvents(self, request, context):
        """Event sourcing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddCron(self, request, context):
        """Cron management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveCron(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCron(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SpawnChild': grpc.unary_unary_rpc_method_handler(
                    servicer.SpawnChild,
                    request_deserializer=agent__pb2.SpawnRequest.FromString,
                    response_serializer=agent__pb2.SpawnResponse.SerializeToString,
            ),
            'KillChild': grpc.unary_unary_rpc_method_handler(
                    servicer.KillChild,
                    request_deserializer=agent__pb2.KillRequest.FromString,
                    response_serializer=agent__pb2.KillResponse.SerializeToString,
            ),
            'GetProcessInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProcessInfo,
                    request_deserializer=core__pb2.ProcessInfoRequest.FromString,
                    response_serializer=core__pb2.ProcessInfo.SerializeToString,
            ),
            'ListChildren': grpc.unary_unary_rpc_method_handler(
                    servicer.ListChildren,
                    request_deserializer=core__pb2.ListChildrenRequest.FromString,
                    response_serializer=core__pb2.ListChildrenResponse.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=agent__pb2.SendMessageRequest.FromString,
                    response_serializer=agent__pb2.SendMessageResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=core__pb2.SubscribeRequest.FromString,
                    response_serializer=agent__pb2.AgentMessage.SerializeToString,
            ),
            'StoreArtifact': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreArtifact,
                    request_deserializer=agent__pb2.StoreArtifactRequest.FromString,
                    response_serializer=agent__pb2.StoreArtifactResponse.SerializeToString,
            ),
            'GetArtifact': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArtifact,
                    request_deserializer=agent__pb2.GetArtifactRequest.FromString,
                    response_serializer=agent__pb2.GetArtifactResponse.SerializeToString,
            ),
            'ListArtifacts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListArtifacts,
                    request_deserializer=core__pb2.ListArtifactsRequest.FromString,
                    response_serializer=core__pb2.ListArtifactsResponse.SerializeToString,
            ),
            'GetResourceUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResourceUsage,
                    request_deserializer=core__pb2.ResourceUsageRequest.FromString,
                    response_serializer=core__pb2.ResourceUsage.SerializeToString,
            ),
            'RequestResources': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestResources,
                    request_deserializer=core__pb2.ResourceRequest.FromString,
                    response_serializer=core__pb2.ResourceResponse.SerializeToString,
            ),
            'Escalate': grpc.unary_unary_rpc_method_handler(
                    servicer.Escalate,
                    request_deserializer=agent__pb2.EscalateRequest.FromString,
                    response_serializer=agent__pb2.EscalateResponse.SerializeToString,
            ),
            'Log': grpc.unary_unary_rpc_method_handler(
                    servicer.Log,
                    request_deserializer=agent__pb2.LogRequest.FromString,
                    response_serializer=agent__pb2.LogResponse.SerializeToString,
            ),
            'ReportMetric': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportMetric,
                    request_deserializer=core__pb2.MetricRequest.FromString,
                    response_serializer=core__pb2.MetricResponse.SerializeToString,
            ),
            'ExecuteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTask,
                    request_deserializer=core__pb2.ExecuteTaskRequest.FromString,
                    response_serializer=core__pb2.ExecuteTaskResponse.SerializeToString,
            ),
            'SubscribeEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEvents,
                    request_deserializer=core__pb2.SubscribeEventsRequest.FromString,
                    response_serializer=core__pb2.ProcessEvent.SerializeToString,
            ),
            'AddCron': grpc.unary_unary_rpc_method_handler(
                    servicer.AddCron,
                    request_deserializer=core__pb2.AddCronRequest.FromString,
                    response_serializer=core__pb2.AddCronResponse.SerializeToString,
            ),
            'RemoveCron': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveCron,
                    request_deserializer=core__pb2.RemoveCronRequest.FromString,
                    response_serializer=core__pb2.RemoveCronResponse.SerializeToString,
            ),
            'ListCron': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCron,
                    request_deserializer=core__pb2.ListCronRequest.FromString,
                    response_serializer=core__pb2.ListCronResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hivekernel.core.CoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hivekernel.core.CoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoreService(object):
    """─── CoreService — provided by core, called by agents ───

    """

    @staticmethod
    def SpawnChild(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivekernel.core.CoreService/SpawnChild',
            agent__pb2.SpawnRequest.SerializeToString,
            agent__pb2.SpawnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KillChild(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivekernel.core.CoreService/KillChild',
            agent__pb2.KillRequest.SerializeToString,
            agent__pb2.KillResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProcessInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivekernel.core.CoreService/GetProcessInfo',
            core__pb2.ProcessInfoRequest.SerializeToString,
            core__pb2.ProcessInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListChildren(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivekernel.core.CoreService/ListChildren',
            core__pb2.ListChildrenRequest.SerializeToString,
            core__pb2.ListChildrenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivekernel.core.CoreService/SendMessage',
            agent__pb2.SendMessageRequest.SerializeToString,
            agent__pb2.SendMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hivekernel.core.CoreService/Subscribe',
            core__pb2.SubscribeRequest.SerializeToString,
            agent__pb2.AgentMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivekernel.core.CoreService/StoreArtifact',
            agent__pb2.StoreArtifactRequest.SerializeToString,
            agent__pb2.StoreArtifactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivekernel.core.CoreService/GetArtifact',
            agent__pb2.GetArtifactRequest.SerializeToString,
            agent__pb2.GetArtifactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListArtifacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivekernel.core.CoreService/ListArtifacts',
            core__pb2.ListArtifactsRequest.SerializeToString,
            core__pb2.ListArtifactsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResourceUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivekernel.core.CoreService/GetResourceUsage',
            core__pb2.ResourceUsageRequest.SerializeToString,
            core__pb2.ResourceUsage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestResources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivekernel.core.CoreService/RequestResources',
            core__pb2.ResourceRequest.SerializeToString,
            core__pb2.ResourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Escalate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivekernel.core.CoreService/Escalate',
            agent__pb2.EscalateRequest.SerializeToString,
            agent__pb2.EscalateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Log(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivekernel.core.CoreService/Log',
            agent__pb2.LogRequest.SerializeToString,
            agent__pb2.LogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportMetric(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivekernel.core.CoreService/ReportMetric',
            core__pb2.MetricRequest.SerializeToString,
            core__pb2.MetricResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivekernel.core.CoreService/ExecuteTask',
            core__pb2.ExecuteTaskRequest.SerializeToString,
            core__pb2.ExecuteTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hivekernel.core.CoreService/SubscribeEvents',
            core__pb2.SubscribeEventsRequest.SerializeToString,
            core__pb2.ProcessEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddCron(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivekernel.core.CoreService/AddCron',
            core__pb2.AddCronRequest.SerializeToString,
            core__pb2.AddCronResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveCron(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivekernel.core.CoreService/RemoveCron',
            core__pb2.RemoveCronRequest.SerializeToString,
            core__pb2.RemoveCronResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCron(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hivekernel.core.CoreService/ListCron',
            core__pb2.ListCronRequest.SerializeToString,
            core__pb2.ListCronResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
