// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: core.proto

package hivepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint64                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInfoRequest) Reset() {
	*x = ProcessInfoRequest{}
	mi := &file_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfoRequest) ProtoMessage() {}

func (x *ProcessInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfoRequest.ProtoReflect.Descriptor instead.
func (*ProcessInfoRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessInfoRequest) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type ProcessInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Pid                 uint64                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Ppid                uint64                 `protobuf:"varint,2,opt,name=ppid,proto3" json:"ppid,omitempty"`
	User                string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Name                string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Role                AgentRole              `protobuf:"varint,5,opt,name=role,proto3,enum=hivekernel.agent.AgentRole" json:"role,omitempty"`
	CognitiveTier       CognitiveTier          `protobuf:"varint,6,opt,name=cognitive_tier,json=cognitiveTier,proto3,enum=hivekernel.agent.CognitiveTier" json:"cognitive_tier,omitempty"`
	Model               string                 `protobuf:"bytes,7,opt,name=model,proto3" json:"model,omitempty"`
	State               AgentState             `protobuf:"varint,8,opt,name=state,proto3,enum=hivekernel.agent.AgentState" json:"state,omitempty"`
	Vps                 string                 `protobuf:"bytes,9,opt,name=vps,proto3" json:"vps,omitempty"`
	TokensConsumed      uint64                 `protobuf:"varint,10,opt,name=tokens_consumed,json=tokensConsumed,proto3" json:"tokens_consumed,omitempty"`
	ContextUsagePercent float32                `protobuf:"fixed32,11,opt,name=context_usage_percent,json=contextUsagePercent,proto3" json:"context_usage_percent,omitempty"`
	ChildCount          uint32                 `protobuf:"varint,12,opt,name=child_count,json=childCount,proto3" json:"child_count,omitempty"`
	StartedAt           uint64                 `protobuf:"varint,13,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CurrentTaskId       string                 `protobuf:"bytes,14,opt,name=current_task_id,json=currentTaskId,proto3" json:"current_task_id,omitempty"`
	RuntimeAddr         string                 `protobuf:"bytes,15,opt,name=runtime_addr,json=runtimeAddr,proto3" json:"runtime_addr,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessInfo) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessInfo) GetPpid() uint64 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *ProcessInfo) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ProcessInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessInfo) GetRole() AgentRole {
	if x != nil {
		return x.Role
	}
	return AgentRole_ROLE_KERNEL
}

func (x *ProcessInfo) GetCognitiveTier() CognitiveTier {
	if x != nil {
		return x.CognitiveTier
	}
	return CognitiveTier_COG_STRATEGIC
}

func (x *ProcessInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ProcessInfo) GetState() AgentState {
	if x != nil {
		return x.State
	}
	return AgentState_STATE_IDLE
}

func (x *ProcessInfo) GetVps() string {
	if x != nil {
		return x.Vps
	}
	return ""
}

func (x *ProcessInfo) GetTokensConsumed() uint64 {
	if x != nil {
		return x.TokensConsumed
	}
	return 0
}

func (x *ProcessInfo) GetContextUsagePercent() float32 {
	if x != nil {
		return x.ContextUsagePercent
	}
	return 0
}

func (x *ProcessInfo) GetChildCount() uint32 {
	if x != nil {
		return x.ChildCount
	}
	return 0
}

func (x *ProcessInfo) GetStartedAt() uint64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *ProcessInfo) GetCurrentTaskId() string {
	if x != nil {
		return x.CurrentTaskId
	}
	return ""
}

func (x *ProcessInfo) GetRuntimeAddr() string {
	if x != nil {
		return x.RuntimeAddr
	}
	return ""
}

type ListChildrenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recursive     bool                   `protobuf:"varint,1,opt,name=recursive,proto3" json:"recursive,omitempty"`
	FilterState   AgentState             `protobuf:"varint,2,opt,name=filter_state,json=filterState,proto3,enum=hivekernel.agent.AgentState" json:"filter_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChildrenRequest) Reset() {
	*x = ListChildrenRequest{}
	mi := &file_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChildrenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChildrenRequest) ProtoMessage() {}

func (x *ListChildrenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChildrenRequest.ProtoReflect.Descriptor instead.
func (*ListChildrenRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{2}
}

func (x *ListChildrenRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

func (x *ListChildrenRequest) GetFilterState() AgentState {
	if x != nil {
		return x.FilterState
	}
	return AgentState_STATE_IDLE
}

type ListChildrenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Children      []*ProcessInfo         `protobuf:"bytes,1,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChildrenResponse) Reset() {
	*x = ListChildrenResponse{}
	mi := &file_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChildrenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChildrenResponse) ProtoMessage() {}

func (x *ListChildrenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChildrenResponse.ProtoReflect.Descriptor instead.
func (*ListChildrenResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{3}
}

func (x *ListChildrenResponse) GetChildren() []*ProcessInfo {
	if x != nil {
		return x.Children
	}
	return nil
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	TypeFilter    string                 `protobuf:"bytes,2,opt,name=type_filter,json=typeFilter,proto3" json:"type_filter,omitempty"`
	MinPriority   Priority               `protobuf:"varint,3,opt,name=min_priority,json=minPriority,proto3,enum=hivekernel.agent.Priority" json:"min_priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *SubscribeRequest) GetTypeFilter() string {
	if x != nil {
		return x.TypeFilter
	}
	return ""
}

func (x *SubscribeRequest) GetMinPriority() Priority {
	if x != nil {
		return x.MinPriority
	}
	return Priority_PRIORITY_CRITICAL
}

type ListArtifactsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	StoredByPid   uint64                 `protobuf:"varint,2,opt,name=stored_by_pid,json=storedByPid,proto3" json:"stored_by_pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArtifactsRequest) Reset() {
	*x = ListArtifactsRequest{}
	mi := &file_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArtifactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtifactsRequest) ProtoMessage() {}

func (x *ListArtifactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArtifactsRequest.ProtoReflect.Descriptor instead.
func (*ListArtifactsRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{5}
}

func (x *ListArtifactsRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ListArtifactsRequest) GetStoredByPid() uint64 {
	if x != nil {
		return x.StoredByPid
	}
	return 0
}

type ListArtifactsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifacts     []*ArtifactMeta        `protobuf:"bytes,1,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArtifactsResponse) Reset() {
	*x = ListArtifactsResponse{}
	mi := &file_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArtifactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtifactsResponse) ProtoMessage() {}

func (x *ListArtifactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArtifactsResponse.ProtoReflect.Descriptor instead.
func (*ListArtifactsResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{6}
}

func (x *ListArtifactsResponse) GetArtifacts() []*ArtifactMeta {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type ArtifactMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	StoredByPid   uint64                 `protobuf:"varint,5,opt,name=stored_by_pid,json=storedByPid,proto3" json:"stored_by_pid,omitempty"`
	StoredAt      uint64                 `protobuf:"varint,6,opt,name=stored_at,json=storedAt,proto3" json:"stored_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactMeta) Reset() {
	*x = ArtifactMeta{}
	mi := &file_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactMeta) ProtoMessage() {}

func (x *ArtifactMeta) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactMeta.ProtoReflect.Descriptor instead.
func (*ArtifactMeta) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{7}
}

func (x *ArtifactMeta) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *ArtifactMeta) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ArtifactMeta) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ArtifactMeta) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ArtifactMeta) GetStoredByPid() uint64 {
	if x != nil {
		return x.StoredByPid
	}
	return 0
}

func (x *ArtifactMeta) GetStoredAt() uint64 {
	if x != nil {
		return x.StoredAt
	}
	return 0
}

type ResourceUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceUsageRequest) Reset() {
	*x = ResourceUsageRequest{}
	mi := &file_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceUsageRequest) ProtoMessage() {}

func (x *ResourceUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceUsageRequest.ProtoReflect.Descriptor instead.
func (*ResourceUsageRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{8}
}

type ResourceUsage struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TokensConsumed      uint64                 `protobuf:"varint,1,opt,name=tokens_consumed,json=tokensConsumed,proto3" json:"tokens_consumed,omitempty"`
	TokensRemaining     uint64                 `protobuf:"varint,2,opt,name=tokens_remaining,json=tokensRemaining,proto3" json:"tokens_remaining,omitempty"`
	ChildrenActive      uint32                 `protobuf:"varint,3,opt,name=children_active,json=childrenActive,proto3" json:"children_active,omitempty"`
	ChildrenMax         uint32                 `protobuf:"varint,4,opt,name=children_max,json=childrenMax,proto3" json:"children_max,omitempty"`
	ContextUsagePercent float32                `protobuf:"fixed32,5,opt,name=context_usage_percent,json=contextUsagePercent,proto3" json:"context_usage_percent,omitempty"`
	UptimeSeconds       uint64                 `protobuf:"varint,6,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ResourceUsage) Reset() {
	*x = ResourceUsage{}
	mi := &file_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceUsage) ProtoMessage() {}

func (x *ResourceUsage) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceUsage.ProtoReflect.Descriptor instead.
func (*ResourceUsage) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{9}
}

func (x *ResourceUsage) GetTokensConsumed() uint64 {
	if x != nil {
		return x.TokensConsumed
	}
	return 0
}

func (x *ResourceUsage) GetTokensRemaining() uint64 {
	if x != nil {
		return x.TokensRemaining
	}
	return 0
}

func (x *ResourceUsage) GetChildrenActive() uint32 {
	if x != nil {
		return x.ChildrenActive
	}
	return 0
}

func (x *ResourceUsage) GetChildrenMax() uint32 {
	if x != nil {
		return x.ChildrenMax
	}
	return 0
}

func (x *ResourceUsage) GetContextUsagePercent() float32 {
	if x != nil {
		return x.ContextUsagePercent
	}
	return 0
}

func (x *ResourceUsage) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type ResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceType  string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Justification string                 `protobuf:"bytes,3,opt,name=justification,proto3" json:"justification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRequest) Reset() {
	*x = ResourceRequest{}
	mi := &file_core_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequest) ProtoMessage() {}

func (x *ResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequest.ProtoReflect.Descriptor instead.
func (*ResourceRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{10}
}

func (x *ResourceRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *ResourceRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ResourceRequest) GetJustification() string {
	if x != nil {
		return x.Justification
	}
	return ""
}

type ResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Granted       bool                   `protobuf:"varint,1,opt,name=granted,proto3" json:"granted,omitempty"`
	GrantedAmount uint64                 `protobuf:"varint,2,opt,name=granted_amount,json=grantedAmount,proto3" json:"granted_amount,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceResponse) Reset() {
	*x = ResourceResponse{}
	mi := &file_core_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceResponse) ProtoMessage() {}

func (x *ResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceResponse.ProtoReflect.Descriptor instead.
func (*ResourceResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{11}
}

func (x *ResourceResponse) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

func (x *ResourceResponse) GetGrantedAmount() uint64 {
	if x != nil {
		return x.GrantedAmount
	}
	return 0
}

func (x *ResourceResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type MetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricRequest) Reset() {
	*x = MetricRequest{}
	mi := &file_core_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricRequest) ProtoMessage() {}

func (x *MetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricRequest.ProtoReflect.Descriptor instead.
func (*MetricRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{12}
}

func (x *MetricRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type MetricResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricResponse) Reset() {
	*x = MetricResponse{}
	mi := &file_core_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricResponse) ProtoMessage() {}

func (x *MetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricResponse.ProtoReflect.Descriptor instead.
func (*MetricResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{13}
}

type ExecuteTaskRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetPid      uint64                 `protobuf:"varint,1,opt,name=target_pid,json=targetPid,proto3" json:"target_pid,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Params         map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutSeconds int32                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteTaskRequest) Reset() {
	*x = ExecuteTaskRequest{}
	mi := &file_core_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTaskRequest) ProtoMessage() {}

func (x *ExecuteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTaskRequest.ProtoReflect.Descriptor instead.
func (*ExecuteTaskRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{14}
}

func (x *ExecuteTaskRequest) GetTargetPid() uint64 {
	if x != nil {
		return x.TargetPid
	}
	return 0
}

func (x *ExecuteTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ExecuteTaskRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ExecuteTaskRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type ExecuteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Result        *TaskResult            `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTaskResponse) Reset() {
	*x = ExecuteTaskResponse{}
	mi := &file_core_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTaskResponse) ProtoMessage() {}

func (x *ExecuteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTaskResponse.ProtoReflect.Descriptor instead.
func (*ExecuteTaskResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{15}
}

func (x *ExecuteTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteTaskResponse) GetResult() *TaskResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ExecuteTaskResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ProcessEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Seq            uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	TimestampMs    int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // "spawned", "state_changed", "removed", "log", "llm_call", "tool_call", "cron_executed"
	Pid            uint64                 `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`
	Ppid           uint64                 `protobuf:"varint,5,opt,name=ppid,proto3" json:"ppid,omitempty"`
	Name           string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Role           string                 `protobuf:"bytes,7,opt,name=role,proto3" json:"role,omitempty"`
	Tier           string                 `protobuf:"bytes,8,opt,name=tier,proto3" json:"tier,omitempty"`
	Model          string                 `protobuf:"bytes,9,opt,name=model,proto3" json:"model,omitempty"`
	State          string                 `protobuf:"bytes,10,opt,name=state,proto3" json:"state,omitempty"`
	OldState       string                 `protobuf:"bytes,11,opt,name=old_state,json=oldState,proto3" json:"old_state,omitempty"`
	NewState       string                 `protobuf:"bytes,12,opt,name=new_state,json=newState,proto3" json:"new_state,omitempty"`
	Level          string                 `protobuf:"bytes,13,opt,name=level,proto3" json:"level,omitempty"`
	Message        string                 `protobuf:"bytes,14,opt,name=message,proto3" json:"message,omitempty"`
	ReplyTo        string                 `protobuf:"bytes,15,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	PayloadPreview string                 `protobuf:"bytes,16,opt,name=payload_preview,json=payloadPreview,proto3" json:"payload_preview,omitempty"`
	TraceId        string                 `protobuf:"bytes,17,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	TraceSpan      string                 `protobuf:"bytes,18,opt,name=trace_span,json=traceSpan,proto3" json:"trace_span,omitempty"`
	MessageId      string                 `protobuf:"bytes,19,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Fields         map[string]string      `protobuf:"bytes,20,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // structured metadata for typed events
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessEvent) Reset() {
	*x = ProcessEvent{}
	mi := &file_core_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessEvent) ProtoMessage() {}

func (x *ProcessEvent) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessEvent.ProtoReflect.Descriptor instead.
func (*ProcessEvent) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{16}
}

func (x *ProcessEvent) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ProcessEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *ProcessEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProcessEvent) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessEvent) GetPpid() uint64 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *ProcessEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessEvent) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ProcessEvent) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *ProcessEvent) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ProcessEvent) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ProcessEvent) GetOldState() string {
	if x != nil {
		return x.OldState
	}
	return ""
}

func (x *ProcessEvent) GetNewState() string {
	if x != nil {
		return x.NewState
	}
	return ""
}

func (x *ProcessEvent) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *ProcessEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProcessEvent) GetReplyTo() string {
	if x != nil {
		return x.ReplyTo
	}
	return ""
}

func (x *ProcessEvent) GetPayloadPreview() string {
	if x != nil {
		return x.PayloadPreview
	}
	return ""
}

func (x *ProcessEvent) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ProcessEvent) GetTraceSpan() string {
	if x != nil {
		return x.TraceSpan
	}
	return ""
}

func (x *ProcessEvent) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ProcessEvent) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type SubscribeEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SinceSeq      uint64                 `protobuf:"varint,1,opt,name=since_seq,json=sinceSeq,proto3" json:"since_seq,omitempty"` // 0 = from now, >0 = replay from seq
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeEventsRequest) Reset() {
	*x = SubscribeEventsRequest{}
	mi := &file_core_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventsRequest) ProtoMessage() {}

func (x *SubscribeEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeEventsRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{17}
}

func (x *SubscribeEventsRequest) GetSinceSeq() uint64 {
	if x != nil {
		return x.SinceSeq
	}
	return 0
}

type CronEntryProto struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CronExpression     string                 `protobuf:"bytes,3,opt,name=cron_expression,json=cronExpression,proto3" json:"cron_expression,omitempty"`
	Action             string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"` // "spawn", "wake", "execute"
	TargetPid          uint64                 `protobuf:"varint,5,opt,name=target_pid,json=targetPid,proto3" json:"target_pid,omitempty"`
	ExecuteDescription string                 `protobuf:"bytes,6,opt,name=execute_description,json=executeDescription,proto3" json:"execute_description,omitempty"`
	ExecuteParams      map[string]string      `protobuf:"bytes,7,rep,name=execute_params,json=executeParams,proto3" json:"execute_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Enabled            bool                   `protobuf:"varint,8,opt,name=enabled,proto3" json:"enabled,omitempty"`
	LastRunMs          int64                  `protobuf:"varint,9,opt,name=last_run_ms,json=lastRunMs,proto3" json:"last_run_ms,omitempty"`
	NextRunMs          int64                  `protobuf:"varint,10,opt,name=next_run_ms,json=nextRunMs,proto3" json:"next_run_ms,omitempty"`
	LastExitCode       int32                  `protobuf:"varint,11,opt,name=last_exit_code,json=lastExitCode,proto3" json:"last_exit_code,omitempty"`
	LastOutput         string                 `protobuf:"bytes,12,opt,name=last_output,json=lastOutput,proto3" json:"last_output,omitempty"`
	LastDurationMs     int64                  `protobuf:"varint,13,opt,name=last_duration_ms,json=lastDurationMs,proto3" json:"last_duration_ms,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CronEntryProto) Reset() {
	*x = CronEntryProto{}
	mi := &file_core_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronEntryProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronEntryProto) ProtoMessage() {}

func (x *CronEntryProto) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronEntryProto.ProtoReflect.Descriptor instead.
func (*CronEntryProto) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{18}
}

func (x *CronEntryProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CronEntryProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CronEntryProto) GetCronExpression() string {
	if x != nil {
		return x.CronExpression
	}
	return ""
}

func (x *CronEntryProto) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CronEntryProto) GetTargetPid() uint64 {
	if x != nil {
		return x.TargetPid
	}
	return 0
}

func (x *CronEntryProto) GetExecuteDescription() string {
	if x != nil {
		return x.ExecuteDescription
	}
	return ""
}

func (x *CronEntryProto) GetExecuteParams() map[string]string {
	if x != nil {
		return x.ExecuteParams
	}
	return nil
}

func (x *CronEntryProto) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CronEntryProto) GetLastRunMs() int64 {
	if x != nil {
		return x.LastRunMs
	}
	return 0
}

func (x *CronEntryProto) GetNextRunMs() int64 {
	if x != nil {
		return x.NextRunMs
	}
	return 0
}

func (x *CronEntryProto) GetLastExitCode() int32 {
	if x != nil {
		return x.LastExitCode
	}
	return 0
}

func (x *CronEntryProto) GetLastOutput() string {
	if x != nil {
		return x.LastOutput
	}
	return ""
}

func (x *CronEntryProto) GetLastDurationMs() int64 {
	if x != nil {
		return x.LastDurationMs
	}
	return 0
}

type AddCronRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CronExpression     string                 `protobuf:"bytes,2,opt,name=cron_expression,json=cronExpression,proto3" json:"cron_expression,omitempty"`
	Action             string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"` // "execute" (default), "spawn", "wake"
	TargetPid          uint64                 `protobuf:"varint,4,opt,name=target_pid,json=targetPid,proto3" json:"target_pid,omitempty"`
	ExecuteDescription string                 `protobuf:"bytes,5,opt,name=execute_description,json=executeDescription,proto3" json:"execute_description,omitempty"`
	ExecuteParams      map[string]string      `protobuf:"bytes,6,rep,name=execute_params,json=executeParams,proto3" json:"execute_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AddCronRequest) Reset() {
	*x = AddCronRequest{}
	mi := &file_core_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCronRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCronRequest) ProtoMessage() {}

func (x *AddCronRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCronRequest.ProtoReflect.Descriptor instead.
func (*AddCronRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{19}
}

func (x *AddCronRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddCronRequest) GetCronExpression() string {
	if x != nil {
		return x.CronExpression
	}
	return ""
}

func (x *AddCronRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AddCronRequest) GetTargetPid() uint64 {
	if x != nil {
		return x.TargetPid
	}
	return 0
}

func (x *AddCronRequest) GetExecuteDescription() string {
	if x != nil {
		return x.ExecuteDescription
	}
	return ""
}

func (x *AddCronRequest) GetExecuteParams() map[string]string {
	if x != nil {
		return x.ExecuteParams
	}
	return nil
}

type AddCronResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CronId        string                 `protobuf:"bytes,1,opt,name=cron_id,json=cronId,proto3" json:"cron_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCronResponse) Reset() {
	*x = AddCronResponse{}
	mi := &file_core_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCronResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCronResponse) ProtoMessage() {}

func (x *AddCronResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCronResponse.ProtoReflect.Descriptor instead.
func (*AddCronResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{20}
}

func (x *AddCronResponse) GetCronId() string {
	if x != nil {
		return x.CronId
	}
	return ""
}

func (x *AddCronResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RemoveCronRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CronId        string                 `protobuf:"bytes,1,opt,name=cron_id,json=cronId,proto3" json:"cron_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCronRequest) Reset() {
	*x = RemoveCronRequest{}
	mi := &file_core_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCronRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCronRequest) ProtoMessage() {}

func (x *RemoveCronRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCronRequest.ProtoReflect.Descriptor instead.
func (*RemoveCronRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{21}
}

func (x *RemoveCronRequest) GetCronId() string {
	if x != nil {
		return x.CronId
	}
	return ""
}

type RemoveCronResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCronResponse) Reset() {
	*x = RemoveCronResponse{}
	mi := &file_core_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCronResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCronResponse) ProtoMessage() {}

func (x *RemoveCronResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCronResponse.ProtoReflect.Descriptor instead.
func (*RemoveCronResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{22}
}

func (x *RemoveCronResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RemoveCronResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListCronRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCronRequest) Reset() {
	*x = ListCronRequest{}
	mi := &file_core_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCronRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCronRequest) ProtoMessage() {}

func (x *ListCronRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCronRequest.ProtoReflect.Descriptor instead.
func (*ListCronRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{23}
}

type ListCronResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*CronEntryProto      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCronResponse) Reset() {
	*x = ListCronResponse{}
	mi := &file_core_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCronResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCronResponse) ProtoMessage() {}

func (x *ListCronResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCronResponse.ProtoReflect.Descriptor instead.
func (*ListCronResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{24}
}

func (x *ListCronResponse) GetEntries() []*CronEntryProto {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ListInboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint64                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInboxRequest) Reset() {
	*x = ListInboxRequest{}
	mi := &file_core_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInboxRequest) ProtoMessage() {}

func (x *ListInboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInboxRequest.ProtoReflect.Descriptor instead.
func (*ListInboxRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{25}
}

func (x *ListInboxRequest) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type ListInboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*AgentMessage        `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInboxResponse) Reset() {
	*x = ListInboxResponse{}
	mi := &file_core_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInboxResponse) ProtoMessage() {}

func (x *ListInboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInboxResponse.ProtoReflect.Descriptor instead.
func (*ListInboxResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{26}
}

func (x *ListInboxResponse) GetMessages() []*AgentMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListInboxResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_core_proto protoreflect.FileDescriptor

const file_core_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"core.proto\x12\x0fhivekernel.core\x1a\vagent.proto\"&\n" +
	"\x12ProcessInfoRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x04R\x03pid\"\x98\x04\n" +
	"\vProcessInfo\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x04R\x03pid\x12\x12\n" +
	"\x04ppid\x18\x02 \x01(\x04R\x04ppid\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12/\n" +
	"\x04role\x18\x05 \x01(\x0e2\x1b.hivekernel.agent.AgentRoleR\x04role\x12F\n" +
	"\x0ecognitive_tier\x18\x06 \x01(\x0e2\x1f.hivekernel.agent.CognitiveTierR\rcognitiveTier\x12\x14\n" +
	"\x05model\x18\a \x01(\tR\x05model\x122\n" +
	"\x05state\x18\b \x01(\x0e2\x1c.hivekernel.agent.AgentStateR\x05state\x12\x10\n" +
	"\x03vps\x18\t \x01(\tR\x03vps\x12'\n" +
	"\x0ftokens_consumed\x18\n" +
	" \x01(\x04R\x0etokensConsumed\x122\n" +
	"\x15context_usage_percent\x18\v \x01(\x02R\x13contextUsagePercent\x12\x1f\n" +
	"\vchild_count\x18\f \x01(\rR\n" +
	"childCount\x12\x1d\n" +
	"\n" +
	"started_at\x18\r \x01(\x04R\tstartedAt\x12&\n" +
	"\x0fcurrent_task_id\x18\x0e \x01(\tR\rcurrentTaskId\x12!\n" +
	"\fruntime_addr\x18\x0f \x01(\tR\vruntimeAddr\"t\n" +
	"\x13ListChildrenRequest\x12\x1c\n" +
	"\trecursive\x18\x01 \x01(\bR\trecursive\x12?\n" +
	"\ffilter_state\x18\x02 \x01(\x0e2\x1c.hivekernel.agent.AgentStateR\vfilterState\"P\n" +
	"\x14ListChildrenResponse\x128\n" +
	"\bchildren\x18\x01 \x03(\v2\x1c.hivekernel.core.ProcessInfoR\bchildren\"\x88\x01\n" +
	"\x10SubscribeRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12\x1f\n" +
	"\vtype_filter\x18\x02 \x01(\tR\n" +
	"typeFilter\x12=\n" +
	"\fmin_priority\x18\x03 \x01(\x0e2\x1a.hivekernel.agent.PriorityR\vminPriority\"R\n" +
	"\x14ListArtifactsRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\"\n" +
	"\rstored_by_pid\x18\x02 \x01(\x04R\vstoredByPid\"T\n" +
	"\x15ListArtifactsResponse\x12;\n" +
	"\tartifacts\x18\x01 \x03(\v2\x1d.hivekernel.core.ArtifactMetaR\tartifacts\"\xc4\x01\n" +
	"\fArtifactMeta\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x04R\tsizeBytes\x12\"\n" +
	"\rstored_by_pid\x18\x05 \x01(\x04R\vstoredByPid\x12\x1b\n" +
	"\tstored_at\x18\x06 \x01(\x04R\bstoredAt\"\x16\n" +
	"\x14ResourceUsageRequest\"\x8a\x02\n" +
	"\rResourceUsage\x12'\n" +
	"\x0ftokens_consumed\x18\x01 \x01(\x04R\x0etokensConsumed\x12)\n" +
	"\x10tokens_remaining\x18\x02 \x01(\x04R\x0ftokensRemaining\x12'\n" +
	"\x0fchildren_active\x18\x03 \x01(\rR\x0echildrenActive\x12!\n" +
	"\fchildren_max\x18\x04 \x01(\rR\vchildrenMax\x122\n" +
	"\x15context_usage_percent\x18\x05 \x01(\x02R\x13contextUsagePercent\x12%\n" +
	"\x0euptime_seconds\x18\x06 \x01(\x04R\ruptimeSeconds\"t\n" +
	"\x0fResourceRequest\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\x12$\n" +
	"\rjustification\x18\x03 \x01(\tR\rjustification\"k\n" +
	"\x10ResourceResponse\x12\x18\n" +
	"\agranted\x18\x01 \x01(\bR\agranted\x12%\n" +
	"\x0egranted_amount\x18\x02 \x01(\x04R\rgrantedAmount\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xb8\x01\n" +
	"\rMetricRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12B\n" +
	"\x06labels\x18\x03 \x03(\v2*.hivekernel.core.MetricRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x10\n" +
	"\x0eMetricResponse\"\x82\x02\n" +
	"\x12ExecuteTaskRequest\x12\x1d\n" +
	"\n" +
	"target_pid\x18\x01 \x01(\x04R\ttargetPid\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12G\n" +
	"\x06params\x18\x03 \x03(\v2/.hivekernel.core.ExecuteTaskRequest.ParamsEntryR\x06params\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"{\n" +
	"\x13ExecuteTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x124\n" +
	"\x06result\x18\x02 \x01(\v2\x1c.hivekernel.agent.TaskResultR\x06result\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xea\x04\n" +
	"\fProcessEvent\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x10\n" +
	"\x03pid\x18\x04 \x01(\x04R\x03pid\x12\x12\n" +
	"\x04ppid\x18\x05 \x01(\x04R\x04ppid\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\a \x01(\tR\x04role\x12\x12\n" +
	"\x04tier\x18\b \x01(\tR\x04tier\x12\x14\n" +
	"\x05model\x18\t \x01(\tR\x05model\x12\x14\n" +
	"\x05state\x18\n" +
	" \x01(\tR\x05state\x12\x1b\n" +
	"\told_state\x18\v \x01(\tR\boldState\x12\x1b\n" +
	"\tnew_state\x18\f \x01(\tR\bnewState\x12\x14\n" +
	"\x05level\x18\r \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x0e \x01(\tR\amessage\x12\x19\n" +
	"\breply_to\x18\x0f \x01(\tR\areplyTo\x12'\n" +
	"\x0fpayload_preview\x18\x10 \x01(\tR\x0epayloadPreview\x12\x19\n" +
	"\btrace_id\x18\x11 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"trace_span\x18\x12 \x01(\tR\ttraceSpan\x12\x1d\n" +
	"\n" +
	"message_id\x18\x13 \x01(\tR\tmessageId\x12A\n" +
	"\x06fields\x18\x14 \x03(\v2).hivekernel.core.ProcessEvent.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"5\n" +
	"\x16SubscribeEventsRequest\x12\x1b\n" +
	"\tsince_seq\x18\x01 \x01(\x04R\bsinceSeq\"\xad\x04\n" +
	"\x0eCronEntryProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x0fcron_expression\x18\x03 \x01(\tR\x0ecronExpression\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x1d\n" +
	"\n" +
	"target_pid\x18\x05 \x01(\x04R\ttargetPid\x12/\n" +
	"\x13execute_description\x18\x06 \x01(\tR\x12executeDescription\x12Y\n" +
	"\x0eexecute_params\x18\a \x03(\v22.hivekernel.core.CronEntryProto.ExecuteParamsEntryR\rexecuteParams\x12\x18\n" +
	"\aenabled\x18\b \x01(\bR\aenabled\x12\x1e\n" +
	"\vlast_run_ms\x18\t \x01(\x03R\tlastRunMs\x12\x1e\n" +
	"\vnext_run_ms\x18\n" +
	" \x01(\x03R\tnextRunMs\x12$\n" +
	"\x0elast_exit_code\x18\v \x01(\x05R\flastExitCode\x12\x1f\n" +
	"\vlast_output\x18\f \x01(\tR\n" +
	"lastOutput\x12(\n" +
	"\x10last_duration_ms\x18\r \x01(\x03R\x0elastDurationMs\x1a@\n" +
	"\x12ExecuteParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd2\x02\n" +
	"\x0eAddCronRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x0fcron_expression\x18\x02 \x01(\tR\x0ecronExpression\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x1d\n" +
	"\n" +
	"target_pid\x18\x04 \x01(\x04R\ttargetPid\x12/\n" +
	"\x13execute_description\x18\x05 \x01(\tR\x12executeDescription\x12Y\n" +
	"\x0eexecute_params\x18\x06 \x03(\v22.hivekernel.core.AddCronRequest.ExecuteParamsEntryR\rexecuteParams\x1a@\n" +
	"\x12ExecuteParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"@\n" +
	"\x0fAddCronResponse\x12\x17\n" +
	"\acron_id\x18\x01 \x01(\tR\x06cronId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\",\n" +
	"\x11RemoveCronRequest\x12\x17\n" +
	"\acron_id\x18\x01 \x01(\tR\x06cronId\":\n" +
	"\x12RemoveCronResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x11\n" +
	"\x0fListCronRequest\"M\n" +
	"\x10ListCronResponse\x129\n" +
	"\aentries\x18\x01 \x03(\v2\x1f.hivekernel.core.CronEntryProtoR\aentries\"$\n" +
	"\x10ListInboxRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x04R\x03pid\"e\n" +
	"\x11ListInboxResponse\x12:\n" +
	"\bmessages\x18\x01 \x03(\v2\x1e.hivekernel.agent.AgentMessageR\bmessages\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\xf8\x0e\n" +
	"\vCoreService\x12M\n" +
	"\n" +
	"SpawnChild\x12\x1e.hivekernel.agent.SpawnRequest\x1a\x1f.hivekernel.agent.SpawnResponse\x12J\n" +
	"\tKillChild\x12\x1d.hivekernel.agent.KillRequest\x1a\x1e.hivekernel.agent.KillResponse\x12S\n" +
	"\x0eGetProcessInfo\x12#.hivekernel.core.ProcessInfoRequest\x1a\x1c.hivekernel.core.ProcessInfo\x12[\n" +
	"\fListChildren\x12$.hivekernel.core.ListChildrenRequest\x1a%.hivekernel.core.ListChildrenResponse\x12Z\n" +
	"\vSendMessage\x12$.hivekernel.agent.SendMessageRequest\x1a%.hivekernel.agent.SendMessageResponse\x12P\n" +
	"\tSubscribe\x12!.hivekernel.core.SubscribeRequest\x1a\x1e.hivekernel.agent.AgentMessage0\x01\x12`\n" +
	"\rStoreArtifact\x12&.hivekernel.agent.StoreArtifactRequest\x1a'.hivekernel.agent.StoreArtifactResponse\x12Z\n" +
	"\vGetArtifact\x12$.hivekernel.agent.GetArtifactRequest\x1a%.hivekernel.agent.GetArtifactResponse\x12^\n" +
	"\rListArtifacts\x12%.hivekernel.core.ListArtifactsRequest\x1a&.hivekernel.core.ListArtifactsResponse\x12Y\n" +
	"\x10GetResourceUsage\x12%.hivekernel.core.ResourceUsageRequest\x1a\x1e.hivekernel.core.ResourceUsage\x12W\n" +
	"\x10RequestResources\x12 .hivekernel.core.ResourceRequest\x1a!.hivekernel.core.ResourceResponse\x12Q\n" +
	"\bEscalate\x12!.hivekernel.agent.EscalateRequest\x1a\".hivekernel.agent.EscalateResponse\x12B\n" +
	"\x03Log\x12\x1c.hivekernel.agent.LogRequest\x1a\x1d.hivekernel.agent.LogResponse\x12O\n" +
	"\fReportMetric\x12\x1e.hivekernel.core.MetricRequest\x1a\x1f.hivekernel.core.MetricResponse\x12X\n" +
	"\vExecuteTask\x12#.hivekernel.core.ExecuteTaskRequest\x1a$.hivekernel.core.ExecuteTaskResponse\x12[\n" +
	"\x0fSubscribeEvents\x12'.hivekernel.core.SubscribeEventsRequest\x1a\x1d.hivekernel.core.ProcessEvent0\x01\x12L\n" +
	"\aAddCron\x12\x1f.hivekernel.core.AddCronRequest\x1a .hivekernel.core.AddCronResponse\x12U\n" +
	"\n" +
	"RemoveCron\x12\".hivekernel.core.RemoveCronRequest\x1a#.hivekernel.core.RemoveCronResponse\x12O\n" +
	"\bListCron\x12 .hivekernel.core.ListCronRequest\x1a!.hivekernel.core.ListCronResponse\x12R\n" +
	"\tListInbox\x12!.hivekernel.core.ListInboxRequest\x1a\".hivekernel.core.ListInboxResponse\x12]\n" +
	"\fListSiblings\x12%.hivekernel.agent.ListSiblingsRequest\x1a&.hivekernel.agent.ListSiblingsResponse\x12T\n" +
	"\tWaitChild\x12\".hivekernel.agent.WaitChildRequest\x1a#.hivekernel.agent.WaitChildResponseB2Z0github.com/selemilka/hivekernel/api/proto/hivepbb\x06proto3"

var (
	file_core_proto_rawDescOnce sync.Once
	file_core_proto_rawDescData []byte
)

func file_core_proto_rawDescGZIP() []byte {
	file_core_proto_rawDescOnce.Do(func() {
		file_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)))
	})
	return file_core_proto_rawDescData
}

var file_core_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_core_proto_goTypes = []any{
	(*ProcessInfoRequest)(nil),     // 0: hivekernel.core.ProcessInfoRequest
	(*ProcessInfo)(nil),            // 1: hivekernel.core.ProcessInfo
	(*ListChildrenRequest)(nil),    // 2: hivekernel.core.ListChildrenRequest
	(*ListChildrenResponse)(nil),   // 3: hivekernel.core.ListChildrenResponse
	(*SubscribeRequest)(nil),       // 4: hivekernel.core.SubscribeRequest
	(*ListArtifactsRequest)(nil),   // 5: hivekernel.core.ListArtifactsRequest
	(*ListArtifactsResponse)(nil),  // 6: hivekernel.core.ListArtifactsResponse
	(*ArtifactMeta)(nil),           // 7: hivekernel.core.ArtifactMeta
	(*ResourceUsageRequest)(nil),   // 8: hivekernel.core.ResourceUsageRequest
	(*ResourceUsage)(nil),          // 9: hivekernel.core.ResourceUsage
	(*ResourceRequest)(nil),        // 10: hivekernel.core.ResourceRequest
	(*ResourceResponse)(nil),       // 11: hivekernel.core.ResourceResponse
	(*MetricRequest)(nil),          // 12: hivekernel.core.MetricRequest
	(*MetricResponse)(nil),         // 13: hivekernel.core.MetricResponse
	(*ExecuteTaskRequest)(nil),     // 14: hivekernel.core.ExecuteTaskRequest
	(*ExecuteTaskResponse)(nil),    // 15: hivekernel.core.ExecuteTaskResponse
	(*ProcessEvent)(nil),           // 16: hivekernel.core.ProcessEvent
	(*SubscribeEventsRequest)(nil), // 17: hivekernel.core.SubscribeEventsRequest
	(*CronEntryProto)(nil),         // 18: hivekernel.core.CronEntryProto
	(*AddCronRequest)(nil),         // 19: hivekernel.core.AddCronRequest
	(*AddCronResponse)(nil),        // 20: hivekernel.core.AddCronResponse
	(*RemoveCronRequest)(nil),      // 21: hivekernel.core.RemoveCronRequest
	(*RemoveCronResponse)(nil),     // 22: hivekernel.core.RemoveCronResponse
	(*ListCronRequest)(nil),        // 23: hivekernel.core.ListCronRequest
	(*ListCronResponse)(nil),       // 24: hivekernel.core.ListCronResponse
	(*ListInboxRequest)(nil),       // 25: hivekernel.core.ListInboxRequest
	(*ListInboxResponse)(nil),      // 26: hivekernel.core.ListInboxResponse
	nil,                            // 27: hivekernel.core.MetricRequest.LabelsEntry
	nil,                            // 28: hivekernel.core.ExecuteTaskRequest.ParamsEntry
	nil,                            // 29: hivekernel.core.ProcessEvent.FieldsEntry
	nil,                            // 30: hivekernel.core.CronEntryProto.ExecuteParamsEntry
	nil,                            // 31: hivekernel.core.AddCronRequest.ExecuteParamsEntry
	(AgentRole)(0),                 // 32: hivekernel.agent.AgentRole
	(CognitiveTier)(0),             // 33: hivekernel.agent.CognitiveTier
	(AgentState)(0),                // 34: hivekernel.agent.AgentState
	(Priority)(0),                  // 35: hivekernel.agent.Priority
	(*TaskResult)(nil),             // 36: hivekernel.agent.TaskResult
	(*AgentMessage)(nil),           // 37: hivekernel.agent.AgentMessage
	(*SpawnRequest)(nil),           // 38: hivekernel.agent.SpawnRequest
	(*KillRequest)(nil),            // 39: hivekernel.agent.KillRequest
	(*SendMessageRequest)(nil),     // 40: hivekernel.agent.SendMessageRequest
	(*StoreArtifactRequest)(nil),   // 41: hivekernel.agent.StoreArtifactRequest
	(*GetArtifactRequest)(nil),     // 42: hivekernel.agent.GetArtifactRequest
	(*EscalateRequest)(nil),        // 43: hivekernel.agent.EscalateRequest
	(*LogRequest)(nil),             // 44: hivekernel.agent.LogRequest
	(*ListSiblingsRequest)(nil),    // 45: hivekernel.agent.ListSiblingsRequest
	(*WaitChildRequest)(nil),       // 46: hivekernel.agent.WaitChildRequest
	(*SpawnResponse)(nil),          // 47: hivekernel.agent.SpawnResponse
	(*KillResponse)(nil),           // 48: hivekernel.agent.KillResponse
	(*SendMessageResponse)(nil),    // 49: hivekernel.agent.SendMessageResponse
	(*StoreArtifactResponse)(nil),  // 50: hivekernel.agent.StoreArtifactResponse
	(*GetArtifactResponse)(nil),    // 51: hivekernel.agent.GetArtifactResponse
	(*EscalateResponse)(nil),       // 52: hivekernel.agent.EscalateResponse
	(*LogResponse)(nil),            // 53: hivekernel.agent.LogResponse
	(*ListSiblingsResponse)(nil),   // 54: hivekernel.agent.ListSiblingsResponse
	(*WaitChildResponse)(nil),      // 55: hivekernel.agent.WaitChildResponse
}
var file_core_proto_depIdxs = []int32{
	32, // 0: hivekernel.core.ProcessInfo.role:type_name -> hivekernel.agent.AgentRole
	33, // 1: hivekernel.core.ProcessInfo.cognitive_tier:type_name -> hivekernel.agent.CognitiveTier
	34, // 2: hivekernel.core.ProcessInfo.state:type_name -> hivekernel.agent.AgentState
	34, // 3: hivekernel.core.ListChildrenRequest.filter_state:type_name -> hivekernel.agent.AgentState
	1,  // 4: hivekernel.core.ListChildrenResponse.children:type_name -> hivekernel.core.ProcessInfo
	35, // 5: hivekernel.core.SubscribeRequest.min_priority:type_name -> hivekernel.agent.Priority
	7,  // 6: hivekernel.core.ListArtifactsResponse.artifacts:type_name -> hivekernel.core.ArtifactMeta
	27, // 7: hivekernel.core.MetricRequest.labels:type_name -> hivekernel.core.MetricRequest.LabelsEntry
	28, // 8: hivekernel.core.ExecuteTaskRequest.params:type_name -> hivekernel.core.ExecuteTaskRequest.ParamsEntry
	36, // 9: hivekernel.core.ExecuteTaskResponse.result:type_name -> hivekernel.agent.TaskResult
	29, // 10: hivekernel.core.ProcessEvent.fields:type_name -> hivekernel.core.ProcessEvent.FieldsEntry
	30, // 11: hivekernel.core.CronEntryProto.execute_params:type_name -> hivekernel.core.CronEntryProto.ExecuteParamsEntry
	31, // 12: hivekernel.core.AddCronRequest.execute_params:type_name -> hivekernel.core.AddCronRequest.ExecuteParamsEntry
	18, // 13: hivekernel.core.ListCronResponse.entries:type_name -> hivekernel.core.CronEntryProto
	37, // 14: hivekernel.core.ListInboxResponse.messages:type_name -> hivekernel.agent.AgentMessage
	38, // 15: hivekernel.core.CoreService.SpawnChild:input_type -> hivekernel.agent.SpawnRequest
	39, // 16: hivekernel.core.CoreService.KillChild:input_type -> hivekernel.agent.KillRequest
	0,  // 17: hivekernel.core.CoreService.GetProcessInfo:input_type -> hivekernel.core.ProcessInfoRequest
	2,  // 18: hivekernel.core.CoreService.ListChildren:input_type -> hivekernel.core.ListChildrenRequest
	40, // 19: hivekernel.core.CoreService.SendMessage:input_type -> hivekernel.agent.SendMessageRequest
	4,  // 20: hivekernel.core.CoreService.Subscribe:input_type -> hivekernel.core.SubscribeRequest
	41, // 21: hivekernel.core.CoreService.StoreArtifact:input_type -> hivekernel.agent.StoreArtifactRequest
	42, // 22: hivekernel.core.CoreService.GetArtifact:input_type -> hivekernel.agent.GetArtifactRequest
	5,  // 23: hivekernel.core.CoreService.ListArtifacts:input_type -> hivekernel.core.ListArtifactsRequest
	8,  // 24: hivekernel.core.CoreService.GetResourceUsage:input_type -> hivekernel.core.ResourceUsageRequest
	10, // 25: hivekernel.core.CoreService.RequestResources:input_type -> hivekernel.core.ResourceRequest
	43, // 26: hivekernel.core.CoreService.Escalate:input_type -> hivekernel.agent.EscalateRequest
	44, // 27: hivekernel.core.CoreService.Log:input_type -> hivekernel.agent.LogRequest
	12, // 28: hivekernel.core.CoreService.ReportMetric:input_type -> hivekernel.core.MetricRequest
	14, // 29: hivekernel.core.CoreService.ExecuteTask:input_type -> hivekernel.core.ExecuteTaskRequest
	17, // 30: hivekernel.core.CoreService.SubscribeEvents:input_type -> hivekernel.core.SubscribeEventsRequest
	19, // 31: hivekernel.core.CoreService.AddCron:input_type -> hivekernel.core.AddCronRequest
	21, // 32: hivekernel.core.CoreService.RemoveCron:input_type -> hivekernel.core.RemoveCronRequest
	23, // 33: hivekernel.core.CoreService.ListCron:input_type -> hivekernel.core.ListCronRequest
	25, // 34: hivekernel.core.CoreService.ListInbox:input_type -> hivekernel.core.ListInboxRequest
	45, // 35: hivekernel.core.CoreService.ListSiblings:input_type -> hivekernel.agent.ListSiblingsRequest
	46, // 36: hivekernel.core.CoreService.WaitChild:input_type -> hivekernel.agent.WaitChildRequest
	47, // 37: hivekernel.core.CoreService.SpawnChild:output_type -> hivekernel.agent.SpawnResponse
	48, // 38: hivekernel.core.CoreService.KillChild:output_type -> hivekernel.agent.KillResponse
	1,  // 39: hivekernel.core.CoreService.GetProcessInfo:output_type -> hivekernel.core.ProcessInfo
	3,  // 40: hivekernel.core.CoreService.ListChildren:output_type -> hivekernel.core.ListChildrenResponse
	49, // 41: hivekernel.core.CoreService.SendMessage:output_type -> hivekernel.agent.SendMessageResponse
	37, // 42: hivekernel.core.CoreService.Subscribe:output_type -> hivekernel.agent.AgentMessage
	50, // 43: hivekernel.core.CoreService.StoreArtifact:output_type -> hivekernel.agent.StoreArtifactResponse
	51, // 44: hivekernel.core.CoreService.GetArtifact:output_type -> hivekernel.agent.GetArtifactResponse
	6,  // 45: hivekernel.core.CoreService.ListArtifacts:output_type -> hivekernel.core.ListArtifactsResponse
	9,  // 46: hivekernel.core.CoreService.GetResourceUsage:output_type -> hivekernel.core.ResourceUsage
	11, // 47: hivekernel.core.CoreService.RequestResources:output_type -> hivekernel.core.ResourceResponse
	52, // 48: hivekernel.core.CoreService.Escalate:output_type -> hivekernel.agent.EscalateResponse
	53, // 49: hivekernel.core.CoreService.Log:output_type -> hivekernel.agent.LogResponse
	13, // 50: hivekernel.core.CoreService.ReportMetric:output_type -> hivekernel.core.MetricResponse
	15, // 51: hivekernel.core.CoreService.ExecuteTask:output_type -> hivekernel.core.ExecuteTaskResponse
	16, // 52: hivekernel.core.CoreService.SubscribeEvents:output_type -> hivekernel.core.ProcessEvent
	20, // 53: hivekernel.core.CoreService.AddCron:output_type -> hivekernel.core.AddCronResponse
	22, // 54: hivekernel.core.CoreService.RemoveCron:output_type -> hivekernel.core.RemoveCronResponse
	24, // 55: hivekernel.core.CoreService.ListCron:output_type -> hivekernel.core.ListCronResponse
	26, // 56: hivekernel.core.CoreService.ListInbox:output_type -> hivekernel.core.ListInboxResponse
	54, // 57: hivekernel.core.CoreService.ListSiblings:output_type -> hivekernel.agent.ListSiblingsResponse
	55, // 58: hivekernel.core.CoreService.WaitChild:output_type -> hivekernel.agent.WaitChildResponse
	37, // [37:59] is the sub-list for method output_type
	15, // [15:37] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_core_proto_init() }
func file_core_proto_init() {
	if File_core_proto != nil {
		return
	}
	file_agent_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_proto_goTypes,
		DependencyIndexes: file_core_proto_depIdxs,
		MessageInfos:      file_core_proto_msgTypes,
	}.Build()
	File_core_proto = out.File
	file_core_proto_goTypes = nil
	file_core_proto_depIdxs = nil
}
