// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: core.proto

package hivepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint64                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInfoRequest) Reset() {
	*x = ProcessInfoRequest{}
	mi := &file_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfoRequest) ProtoMessage() {}

func (x *ProcessInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfoRequest.ProtoReflect.Descriptor instead.
func (*ProcessInfoRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessInfoRequest) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type ProcessInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Pid                 uint64                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Ppid                uint64                 `protobuf:"varint,2,opt,name=ppid,proto3" json:"ppid,omitempty"`
	User                string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Name                string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Role                AgentRole              `protobuf:"varint,5,opt,name=role,proto3,enum=hivekernel.agent.AgentRole" json:"role,omitempty"`
	CognitiveTier       CognitiveTier          `protobuf:"varint,6,opt,name=cognitive_tier,json=cognitiveTier,proto3,enum=hivekernel.agent.CognitiveTier" json:"cognitive_tier,omitempty"`
	Model               string                 `protobuf:"bytes,7,opt,name=model,proto3" json:"model,omitempty"`
	State               AgentState             `protobuf:"varint,8,opt,name=state,proto3,enum=hivekernel.agent.AgentState" json:"state,omitempty"`
	Vps                 string                 `protobuf:"bytes,9,opt,name=vps,proto3" json:"vps,omitempty"`
	TokensConsumed      uint64                 `protobuf:"varint,10,opt,name=tokens_consumed,json=tokensConsumed,proto3" json:"tokens_consumed,omitempty"`
	ContextUsagePercent float32                `protobuf:"fixed32,11,opt,name=context_usage_percent,json=contextUsagePercent,proto3" json:"context_usage_percent,omitempty"`
	ChildCount          uint32                 `protobuf:"varint,12,opt,name=child_count,json=childCount,proto3" json:"child_count,omitempty"`
	StartedAt           uint64                 `protobuf:"varint,13,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CurrentTaskId       string                 `protobuf:"bytes,14,opt,name=current_task_id,json=currentTaskId,proto3" json:"current_task_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessInfo) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessInfo) GetPpid() uint64 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *ProcessInfo) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ProcessInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessInfo) GetRole() AgentRole {
	if x != nil {
		return x.Role
	}
	return AgentRole_ROLE_KERNEL
}

func (x *ProcessInfo) GetCognitiveTier() CognitiveTier {
	if x != nil {
		return x.CognitiveTier
	}
	return CognitiveTier_COG_STRATEGIC
}

func (x *ProcessInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ProcessInfo) GetState() AgentState {
	if x != nil {
		return x.State
	}
	return AgentState_STATE_IDLE
}

func (x *ProcessInfo) GetVps() string {
	if x != nil {
		return x.Vps
	}
	return ""
}

func (x *ProcessInfo) GetTokensConsumed() uint64 {
	if x != nil {
		return x.TokensConsumed
	}
	return 0
}

func (x *ProcessInfo) GetContextUsagePercent() float32 {
	if x != nil {
		return x.ContextUsagePercent
	}
	return 0
}

func (x *ProcessInfo) GetChildCount() uint32 {
	if x != nil {
		return x.ChildCount
	}
	return 0
}

func (x *ProcessInfo) GetStartedAt() uint64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *ProcessInfo) GetCurrentTaskId() string {
	if x != nil {
		return x.CurrentTaskId
	}
	return ""
}

type ListChildrenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recursive     bool                   `protobuf:"varint,1,opt,name=recursive,proto3" json:"recursive,omitempty"`
	FilterState   AgentState             `protobuf:"varint,2,opt,name=filter_state,json=filterState,proto3,enum=hivekernel.agent.AgentState" json:"filter_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChildrenRequest) Reset() {
	*x = ListChildrenRequest{}
	mi := &file_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChildrenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChildrenRequest) ProtoMessage() {}

func (x *ListChildrenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChildrenRequest.ProtoReflect.Descriptor instead.
func (*ListChildrenRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{2}
}

func (x *ListChildrenRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

func (x *ListChildrenRequest) GetFilterState() AgentState {
	if x != nil {
		return x.FilterState
	}
	return AgentState_STATE_IDLE
}

type ListChildrenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Children      []*ProcessInfo         `protobuf:"bytes,1,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChildrenResponse) Reset() {
	*x = ListChildrenResponse{}
	mi := &file_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChildrenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChildrenResponse) ProtoMessage() {}

func (x *ListChildrenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChildrenResponse.ProtoReflect.Descriptor instead.
func (*ListChildrenResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{3}
}

func (x *ListChildrenResponse) GetChildren() []*ProcessInfo {
	if x != nil {
		return x.Children
	}
	return nil
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	TypeFilter    string                 `protobuf:"bytes,2,opt,name=type_filter,json=typeFilter,proto3" json:"type_filter,omitempty"`
	MinPriority   Priority               `protobuf:"varint,3,opt,name=min_priority,json=minPriority,proto3,enum=hivekernel.agent.Priority" json:"min_priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *SubscribeRequest) GetTypeFilter() string {
	if x != nil {
		return x.TypeFilter
	}
	return ""
}

func (x *SubscribeRequest) GetMinPriority() Priority {
	if x != nil {
		return x.MinPriority
	}
	return Priority_PRIORITY_CRITICAL
}

type ListArtifactsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	StoredByPid   uint64                 `protobuf:"varint,2,opt,name=stored_by_pid,json=storedByPid,proto3" json:"stored_by_pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArtifactsRequest) Reset() {
	*x = ListArtifactsRequest{}
	mi := &file_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArtifactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtifactsRequest) ProtoMessage() {}

func (x *ListArtifactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArtifactsRequest.ProtoReflect.Descriptor instead.
func (*ListArtifactsRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{5}
}

func (x *ListArtifactsRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ListArtifactsRequest) GetStoredByPid() uint64 {
	if x != nil {
		return x.StoredByPid
	}
	return 0
}

type ListArtifactsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifacts     []*ArtifactMeta        `protobuf:"bytes,1,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArtifactsResponse) Reset() {
	*x = ListArtifactsResponse{}
	mi := &file_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArtifactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtifactsResponse) ProtoMessage() {}

func (x *ListArtifactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArtifactsResponse.ProtoReflect.Descriptor instead.
func (*ListArtifactsResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{6}
}

func (x *ListArtifactsResponse) GetArtifacts() []*ArtifactMeta {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type ArtifactMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	StoredByPid   uint64                 `protobuf:"varint,5,opt,name=stored_by_pid,json=storedByPid,proto3" json:"stored_by_pid,omitempty"`
	StoredAt      uint64                 `protobuf:"varint,6,opt,name=stored_at,json=storedAt,proto3" json:"stored_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactMeta) Reset() {
	*x = ArtifactMeta{}
	mi := &file_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactMeta) ProtoMessage() {}

func (x *ArtifactMeta) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactMeta.ProtoReflect.Descriptor instead.
func (*ArtifactMeta) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{7}
}

func (x *ArtifactMeta) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *ArtifactMeta) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ArtifactMeta) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ArtifactMeta) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ArtifactMeta) GetStoredByPid() uint64 {
	if x != nil {
		return x.StoredByPid
	}
	return 0
}

func (x *ArtifactMeta) GetStoredAt() uint64 {
	if x != nil {
		return x.StoredAt
	}
	return 0
}

type ResourceUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceUsageRequest) Reset() {
	*x = ResourceUsageRequest{}
	mi := &file_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceUsageRequest) ProtoMessage() {}

func (x *ResourceUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceUsageRequest.ProtoReflect.Descriptor instead.
func (*ResourceUsageRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{8}
}

type ResourceUsage struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TokensConsumed      uint64                 `protobuf:"varint,1,opt,name=tokens_consumed,json=tokensConsumed,proto3" json:"tokens_consumed,omitempty"`
	TokensRemaining     uint64                 `protobuf:"varint,2,opt,name=tokens_remaining,json=tokensRemaining,proto3" json:"tokens_remaining,omitempty"`
	ChildrenActive      uint32                 `protobuf:"varint,3,opt,name=children_active,json=childrenActive,proto3" json:"children_active,omitempty"`
	ChildrenMax         uint32                 `protobuf:"varint,4,opt,name=children_max,json=childrenMax,proto3" json:"children_max,omitempty"`
	ContextUsagePercent float32                `protobuf:"fixed32,5,opt,name=context_usage_percent,json=contextUsagePercent,proto3" json:"context_usage_percent,omitempty"`
	UptimeSeconds       uint64                 `protobuf:"varint,6,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ResourceUsage) Reset() {
	*x = ResourceUsage{}
	mi := &file_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceUsage) ProtoMessage() {}

func (x *ResourceUsage) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceUsage.ProtoReflect.Descriptor instead.
func (*ResourceUsage) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{9}
}

func (x *ResourceUsage) GetTokensConsumed() uint64 {
	if x != nil {
		return x.TokensConsumed
	}
	return 0
}

func (x *ResourceUsage) GetTokensRemaining() uint64 {
	if x != nil {
		return x.TokensRemaining
	}
	return 0
}

func (x *ResourceUsage) GetChildrenActive() uint32 {
	if x != nil {
		return x.ChildrenActive
	}
	return 0
}

func (x *ResourceUsage) GetChildrenMax() uint32 {
	if x != nil {
		return x.ChildrenMax
	}
	return 0
}

func (x *ResourceUsage) GetContextUsagePercent() float32 {
	if x != nil {
		return x.ContextUsagePercent
	}
	return 0
}

func (x *ResourceUsage) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type ResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceType  string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Justification string                 `protobuf:"bytes,3,opt,name=justification,proto3" json:"justification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRequest) Reset() {
	*x = ResourceRequest{}
	mi := &file_core_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequest) ProtoMessage() {}

func (x *ResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequest.ProtoReflect.Descriptor instead.
func (*ResourceRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{10}
}

func (x *ResourceRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *ResourceRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ResourceRequest) GetJustification() string {
	if x != nil {
		return x.Justification
	}
	return ""
}

type ResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Granted       bool                   `protobuf:"varint,1,opt,name=granted,proto3" json:"granted,omitempty"`
	GrantedAmount uint64                 `protobuf:"varint,2,opt,name=granted_amount,json=grantedAmount,proto3" json:"granted_amount,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceResponse) Reset() {
	*x = ResourceResponse{}
	mi := &file_core_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceResponse) ProtoMessage() {}

func (x *ResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceResponse.ProtoReflect.Descriptor instead.
func (*ResourceResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{11}
}

func (x *ResourceResponse) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

func (x *ResourceResponse) GetGrantedAmount() uint64 {
	if x != nil {
		return x.GrantedAmount
	}
	return 0
}

func (x *ResourceResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type MetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricRequest) Reset() {
	*x = MetricRequest{}
	mi := &file_core_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricRequest) ProtoMessage() {}

func (x *MetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricRequest.ProtoReflect.Descriptor instead.
func (*MetricRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{12}
}

func (x *MetricRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type MetricResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricResponse) Reset() {
	*x = MetricResponse{}
	mi := &file_core_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricResponse) ProtoMessage() {}

func (x *MetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricResponse.ProtoReflect.Descriptor instead.
func (*MetricResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{13}
}

var File_core_proto protoreflect.FileDescriptor

const file_core_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"core.proto\x12\x0fhivekernel.core\x1a\vagent.proto\"&\n" +
	"\x12ProcessInfoRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x04R\x03pid\"\xf5\x03\n" +
	"\vProcessInfo\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x04R\x03pid\x12\x12\n" +
	"\x04ppid\x18\x02 \x01(\x04R\x04ppid\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12/\n" +
	"\x04role\x18\x05 \x01(\x0e2\x1b.hivekernel.agent.AgentRoleR\x04role\x12F\n" +
	"\x0ecognitive_tier\x18\x06 \x01(\x0e2\x1f.hivekernel.agent.CognitiveTierR\rcognitiveTier\x12\x14\n" +
	"\x05model\x18\a \x01(\tR\x05model\x122\n" +
	"\x05state\x18\b \x01(\x0e2\x1c.hivekernel.agent.AgentStateR\x05state\x12\x10\n" +
	"\x03vps\x18\t \x01(\tR\x03vps\x12'\n" +
	"\x0ftokens_consumed\x18\n" +
	" \x01(\x04R\x0etokensConsumed\x122\n" +
	"\x15context_usage_percent\x18\v \x01(\x02R\x13contextUsagePercent\x12\x1f\n" +
	"\vchild_count\x18\f \x01(\rR\n" +
	"childCount\x12\x1d\n" +
	"\n" +
	"started_at\x18\r \x01(\x04R\tstartedAt\x12&\n" +
	"\x0fcurrent_task_id\x18\x0e \x01(\tR\rcurrentTaskId\"t\n" +
	"\x13ListChildrenRequest\x12\x1c\n" +
	"\trecursive\x18\x01 \x01(\bR\trecursive\x12?\n" +
	"\ffilter_state\x18\x02 \x01(\x0e2\x1c.hivekernel.agent.AgentStateR\vfilterState\"P\n" +
	"\x14ListChildrenResponse\x128\n" +
	"\bchildren\x18\x01 \x03(\v2\x1c.hivekernel.core.ProcessInfoR\bchildren\"\x88\x01\n" +
	"\x10SubscribeRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12\x1f\n" +
	"\vtype_filter\x18\x02 \x01(\tR\n" +
	"typeFilter\x12=\n" +
	"\fmin_priority\x18\x03 \x01(\x0e2\x1a.hivekernel.agent.PriorityR\vminPriority\"R\n" +
	"\x14ListArtifactsRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\"\n" +
	"\rstored_by_pid\x18\x02 \x01(\x04R\vstoredByPid\"T\n" +
	"\x15ListArtifactsResponse\x12;\n" +
	"\tartifacts\x18\x01 \x03(\v2\x1d.hivekernel.core.ArtifactMetaR\tartifacts\"\xc4\x01\n" +
	"\fArtifactMeta\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x04R\tsizeBytes\x12\"\n" +
	"\rstored_by_pid\x18\x05 \x01(\x04R\vstoredByPid\x12\x1b\n" +
	"\tstored_at\x18\x06 \x01(\x04R\bstoredAt\"\x16\n" +
	"\x14ResourceUsageRequest\"\x8a\x02\n" +
	"\rResourceUsage\x12'\n" +
	"\x0ftokens_consumed\x18\x01 \x01(\x04R\x0etokensConsumed\x12)\n" +
	"\x10tokens_remaining\x18\x02 \x01(\x04R\x0ftokensRemaining\x12'\n" +
	"\x0fchildren_active\x18\x03 \x01(\rR\x0echildrenActive\x12!\n" +
	"\fchildren_max\x18\x04 \x01(\rR\vchildrenMax\x122\n" +
	"\x15context_usage_percent\x18\x05 \x01(\x02R\x13contextUsagePercent\x12%\n" +
	"\x0euptime_seconds\x18\x06 \x01(\x04R\ruptimeSeconds\"t\n" +
	"\x0fResourceRequest\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\x12$\n" +
	"\rjustification\x18\x03 \x01(\tR\rjustification\"k\n" +
	"\x10ResourceResponse\x12\x18\n" +
	"\agranted\x18\x01 \x01(\bR\agranted\x12%\n" +
	"\x0egranted_amount\x18\x02 \x01(\x04R\rgrantedAmount\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xb8\x01\n" +
	"\rMetricRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12B\n" +
	"\x06labels\x18\x03 \x03(\v2*.hivekernel.core.MetricRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x10\n" +
	"\x0eMetricResponse2\xc2\t\n" +
	"\vCoreService\x12M\n" +
	"\n" +
	"SpawnChild\x12\x1e.hivekernel.agent.SpawnRequest\x1a\x1f.hivekernel.agent.SpawnResponse\x12J\n" +
	"\tKillChild\x12\x1d.hivekernel.agent.KillRequest\x1a\x1e.hivekernel.agent.KillResponse\x12S\n" +
	"\x0eGetProcessInfo\x12#.hivekernel.core.ProcessInfoRequest\x1a\x1c.hivekernel.core.ProcessInfo\x12[\n" +
	"\fListChildren\x12$.hivekernel.core.ListChildrenRequest\x1a%.hivekernel.core.ListChildrenResponse\x12Z\n" +
	"\vSendMessage\x12$.hivekernel.agent.SendMessageRequest\x1a%.hivekernel.agent.SendMessageResponse\x12P\n" +
	"\tSubscribe\x12!.hivekernel.core.SubscribeRequest\x1a\x1e.hivekernel.agent.AgentMessage0\x01\x12`\n" +
	"\rStoreArtifact\x12&.hivekernel.agent.StoreArtifactRequest\x1a'.hivekernel.agent.StoreArtifactResponse\x12Z\n" +
	"\vGetArtifact\x12$.hivekernel.agent.GetArtifactRequest\x1a%.hivekernel.agent.GetArtifactResponse\x12^\n" +
	"\rListArtifacts\x12%.hivekernel.core.ListArtifactsRequest\x1a&.hivekernel.core.ListArtifactsResponse\x12Y\n" +
	"\x10GetResourceUsage\x12%.hivekernel.core.ResourceUsageRequest\x1a\x1e.hivekernel.core.ResourceUsage\x12W\n" +
	"\x10RequestResources\x12 .hivekernel.core.ResourceRequest\x1a!.hivekernel.core.ResourceResponse\x12Q\n" +
	"\bEscalate\x12!.hivekernel.agent.EscalateRequest\x1a\".hivekernel.agent.EscalateResponse\x12B\n" +
	"\x03Log\x12\x1c.hivekernel.agent.LogRequest\x1a\x1d.hivekernel.agent.LogResponse\x12O\n" +
	"\fReportMetric\x12\x1e.hivekernel.core.MetricRequest\x1a\x1f.hivekernel.core.MetricResponseB2Z0github.com/selemilka/hivekernel/api/proto/hivepbb\x06proto3"

var (
	file_core_proto_rawDescOnce sync.Once
	file_core_proto_rawDescData []byte
)

func file_core_proto_rawDescGZIP() []byte {
	file_core_proto_rawDescOnce.Do(func() {
		file_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)))
	})
	return file_core_proto_rawDescData
}

var file_core_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_core_proto_goTypes = []any{
	(*ProcessInfoRequest)(nil),    // 0: hivekernel.core.ProcessInfoRequest
	(*ProcessInfo)(nil),           // 1: hivekernel.core.ProcessInfo
	(*ListChildrenRequest)(nil),   // 2: hivekernel.core.ListChildrenRequest
	(*ListChildrenResponse)(nil),  // 3: hivekernel.core.ListChildrenResponse
	(*SubscribeRequest)(nil),      // 4: hivekernel.core.SubscribeRequest
	(*ListArtifactsRequest)(nil),  // 5: hivekernel.core.ListArtifactsRequest
	(*ListArtifactsResponse)(nil), // 6: hivekernel.core.ListArtifactsResponse
	(*ArtifactMeta)(nil),          // 7: hivekernel.core.ArtifactMeta
	(*ResourceUsageRequest)(nil),  // 8: hivekernel.core.ResourceUsageRequest
	(*ResourceUsage)(nil),         // 9: hivekernel.core.ResourceUsage
	(*ResourceRequest)(nil),       // 10: hivekernel.core.ResourceRequest
	(*ResourceResponse)(nil),      // 11: hivekernel.core.ResourceResponse
	(*MetricRequest)(nil),         // 12: hivekernel.core.MetricRequest
	(*MetricResponse)(nil),        // 13: hivekernel.core.MetricResponse
	nil,                           // 14: hivekernel.core.MetricRequest.LabelsEntry
	(AgentRole)(0),                // 15: hivekernel.agent.AgentRole
	(CognitiveTier)(0),            // 16: hivekernel.agent.CognitiveTier
	(AgentState)(0),               // 17: hivekernel.agent.AgentState
	(Priority)(0),                 // 18: hivekernel.agent.Priority
	(*SpawnRequest)(nil),          // 19: hivekernel.agent.SpawnRequest
	(*KillRequest)(nil),           // 20: hivekernel.agent.KillRequest
	(*SendMessageRequest)(nil),    // 21: hivekernel.agent.SendMessageRequest
	(*StoreArtifactRequest)(nil),  // 22: hivekernel.agent.StoreArtifactRequest
	(*GetArtifactRequest)(nil),    // 23: hivekernel.agent.GetArtifactRequest
	(*EscalateRequest)(nil),       // 24: hivekernel.agent.EscalateRequest
	(*LogRequest)(nil),            // 25: hivekernel.agent.LogRequest
	(*SpawnResponse)(nil),         // 26: hivekernel.agent.SpawnResponse
	(*KillResponse)(nil),          // 27: hivekernel.agent.KillResponse
	(*SendMessageResponse)(nil),   // 28: hivekernel.agent.SendMessageResponse
	(*AgentMessage)(nil),          // 29: hivekernel.agent.AgentMessage
	(*StoreArtifactResponse)(nil), // 30: hivekernel.agent.StoreArtifactResponse
	(*GetArtifactResponse)(nil),   // 31: hivekernel.agent.GetArtifactResponse
	(*EscalateResponse)(nil),      // 32: hivekernel.agent.EscalateResponse
	(*LogResponse)(nil),           // 33: hivekernel.agent.LogResponse
}
var file_core_proto_depIdxs = []int32{
	15, // 0: hivekernel.core.ProcessInfo.role:type_name -> hivekernel.agent.AgentRole
	16, // 1: hivekernel.core.ProcessInfo.cognitive_tier:type_name -> hivekernel.agent.CognitiveTier
	17, // 2: hivekernel.core.ProcessInfo.state:type_name -> hivekernel.agent.AgentState
	17, // 3: hivekernel.core.ListChildrenRequest.filter_state:type_name -> hivekernel.agent.AgentState
	1,  // 4: hivekernel.core.ListChildrenResponse.children:type_name -> hivekernel.core.ProcessInfo
	18, // 5: hivekernel.core.SubscribeRequest.min_priority:type_name -> hivekernel.agent.Priority
	7,  // 6: hivekernel.core.ListArtifactsResponse.artifacts:type_name -> hivekernel.core.ArtifactMeta
	14, // 7: hivekernel.core.MetricRequest.labels:type_name -> hivekernel.core.MetricRequest.LabelsEntry
	19, // 8: hivekernel.core.CoreService.SpawnChild:input_type -> hivekernel.agent.SpawnRequest
	20, // 9: hivekernel.core.CoreService.KillChild:input_type -> hivekernel.agent.KillRequest
	0,  // 10: hivekernel.core.CoreService.GetProcessInfo:input_type -> hivekernel.core.ProcessInfoRequest
	2,  // 11: hivekernel.core.CoreService.ListChildren:input_type -> hivekernel.core.ListChildrenRequest
	21, // 12: hivekernel.core.CoreService.SendMessage:input_type -> hivekernel.agent.SendMessageRequest
	4,  // 13: hivekernel.core.CoreService.Subscribe:input_type -> hivekernel.core.SubscribeRequest
	22, // 14: hivekernel.core.CoreService.StoreArtifact:input_type -> hivekernel.agent.StoreArtifactRequest
	23, // 15: hivekernel.core.CoreService.GetArtifact:input_type -> hivekernel.agent.GetArtifactRequest
	5,  // 16: hivekernel.core.CoreService.ListArtifacts:input_type -> hivekernel.core.ListArtifactsRequest
	8,  // 17: hivekernel.core.CoreService.GetResourceUsage:input_type -> hivekernel.core.ResourceUsageRequest
	10, // 18: hivekernel.core.CoreService.RequestResources:input_type -> hivekernel.core.ResourceRequest
	24, // 19: hivekernel.core.CoreService.Escalate:input_type -> hivekernel.agent.EscalateRequest
	25, // 20: hivekernel.core.CoreService.Log:input_type -> hivekernel.agent.LogRequest
	12, // 21: hivekernel.core.CoreService.ReportMetric:input_type -> hivekernel.core.MetricRequest
	26, // 22: hivekernel.core.CoreService.SpawnChild:output_type -> hivekernel.agent.SpawnResponse
	27, // 23: hivekernel.core.CoreService.KillChild:output_type -> hivekernel.agent.KillResponse
	1,  // 24: hivekernel.core.CoreService.GetProcessInfo:output_type -> hivekernel.core.ProcessInfo
	3,  // 25: hivekernel.core.CoreService.ListChildren:output_type -> hivekernel.core.ListChildrenResponse
	28, // 26: hivekernel.core.CoreService.SendMessage:output_type -> hivekernel.agent.SendMessageResponse
	29, // 27: hivekernel.core.CoreService.Subscribe:output_type -> hivekernel.agent.AgentMessage
	30, // 28: hivekernel.core.CoreService.StoreArtifact:output_type -> hivekernel.agent.StoreArtifactResponse
	31, // 29: hivekernel.core.CoreService.GetArtifact:output_type -> hivekernel.agent.GetArtifactResponse
	6,  // 30: hivekernel.core.CoreService.ListArtifacts:output_type -> hivekernel.core.ListArtifactsResponse
	9,  // 31: hivekernel.core.CoreService.GetResourceUsage:output_type -> hivekernel.core.ResourceUsage
	11, // 32: hivekernel.core.CoreService.RequestResources:output_type -> hivekernel.core.ResourceResponse
	32, // 33: hivekernel.core.CoreService.Escalate:output_type -> hivekernel.agent.EscalateResponse
	33, // 34: hivekernel.core.CoreService.Log:output_type -> hivekernel.agent.LogResponse
	13, // 35: hivekernel.core.CoreService.ReportMetric:output_type -> hivekernel.core.MetricResponse
	22, // [22:36] is the sub-list for method output_type
	8,  // [8:22] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_core_proto_init() }
func file_core_proto_init() {
	if File_core_proto != nil {
		return
	}
	file_agent_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_proto_goTypes,
		DependencyIndexes: file_core_proto_depIdxs,
		MessageInfos:      file_core_proto_msgTypes,
	}.Build()
	File_core_proto = out.File
	file_core_proto_goTypes = nil
	file_core_proto_depIdxs = nil
}
